algoritmo "semnome"
// Função :
// Autor :
// Data : 21/11/2024
// Seção de Declarações 
var
 valor1, valor2, soma: inteiro
inicio
   // Seção de Comandos
   Escreval( "digite o primeiro valor: ")
   Leia(valor1)
   Escreval("digite o segundo valor: ")
   Leia(valor2)
   
   soma <- valor1 +  valor2
   
   Escreval("O resultadoda soma entre ", valor1, " e ", valor2," é ", soma)

fimalgoritmo
