algoritmo "time"
// Função :
// Autor :
// Data : 25/11/2024
// Seção de Declarações 
var time:  Caractere

inicio
escreva ("Entre com o nome de um time de futebol: ")
leia(time)
escolha time
caso "Flamengo", "Fluminense", "Vasco", "Botafogo"
 escreval ("É um time carioca.")
caso "São Paulo", "Palmeiras", "Santos", "Corínthians"
 escreval ("É um time paulista.")
outrocaso
 escreval ("É de outro estado.")
fimescolha

// Seção de Comandos 
fimalgoritmo
